---
abstract: 'A Cleaner API for Net::AMQP::RabbitMQ'
author:
  - 'Chris Prather <chris@prather.org>'
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.98'
  Test::Net::RabbitMQ: '0.08'
  Test::Requires: '0.06'
  lib: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crixa
requires:
  Moose: '0'
  Moose::Role: '0'
  Net::AMQP::RabbitMQ: '0'
  namespace::autoclean: '0'
  perl: v5.10.0
resources:
  bugtracker: https://github.com/Tamarou/Crixa/issues
  repository: git://github.com/Tamarou/Crixa.git
version: '0.07'
x_contributors:
  - 'Torsten Raudssus <torsten@raudss.us>'
