---
abstract: 'A Cleaner API for Net::RabbitMQ'
author:
  - 'Chris Prather <chris@prather.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  Test::Net::RabbitMQ: 0.08
  Test::Requires: 0.06
  Test::Simple: 0.98
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crixa
requires:
  Moose: 0
  Moose::Role: 0
  Net::RabbitMQ: 0
  namespace::autoclean: 0
  perl: v5.10.0
version: 0.01
