
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
DROLSKY
DROLSKY's
Rolsky
Rolsky's
AMQP
GitHub
QoS
ack
acks
api
hostname
metadata
prefetched
prefetching
timestamp
undeliverable
unroutable
username
utf
webcrawler
Chris
Prather
chris
Dave
autarch
Torsten
Raudssus
torsten
lib
Crixa
Message
Exchange
Engine
RabbitMQ
Queue
Channel
API
